### ISSUE TITLE
想问一下作者可不可以开发成一个刷代币的脚本插件，可以有偿费用支援，最近星之守护者事件开启了，但是一直没能找到合适的脚本插件帮忙实现代刷代币，肝游戏真的非常的费时间，希望可以帮帮忙感谢。qq1975255575，希望可以考虑一下，这边可以帮忙售卖。

### ISSUE THREAD

**Issue by masked-ken** [xzhy324/TFTAuto#2]
想问一下作者可不可以开发成一个刷代币的脚本插件，可以有偿费用支援，最近星之守护者事件开启了，但是一直没能找到合适的脚本插件帮忙实现代刷代币，肝游戏真的非常的费时间，希望可以帮帮忙感谢。qq1975255575，希望可以考虑一下，这边可以帮忙售卖。

**Comment by xzhy324** [comment]
你好！目前没有商业化的打算。祝好！
