### ISSUE TITLE
完善一下运行步骤吧

### ISSUE THREAD

**Issue by losanming** [xzhy324/TFTAuto#4]
哥们，我没写过python但是对你的项目很感兴趣，但是苦于没怎么接触过python，所以能抽空完善一下readme的使用步骤嘛

**Comment by xzhy324** [comment]
运行步骤
1. 安装PyQt5，requests， pyautogui， pynput库
2. python main.py

可能的问题：
1.  simulator.py下的百度ocr api可能已经作废，需要你自己重新注册一个填进去
2.  spider.py下从https://game.gtimg.cn/images/lol/act/img/tft/js/* 获取的js格式可能发生变化，解析逻辑需要你自己重写

另：这个项目在s6完成，已经一年多没有维护，如果你适配了s9，欢迎提PR :)
